CT-11/CT-50
connectattoo/connectattoo.android pull request #14
Opened 2023-12-24 20:17 UTC by felipemorilho

Tela de confirmação de cadastro do cliente e tatuador.

Foi mexido na lógica do botão de criar conta, para poder fazer a condicional dos campos de endereço do tatuador.

Por isso, criei uma abstract fun conditionCheking, que é implementada nas respectivas classes com as condições necessárias.

2023-12-28 01:01 UTC, natanaelsc commented on app/src/main/java/br/com/connectattoo/ui/confirmation/ConfirmationFragment.kt
> +    override fun onCreateView(
Não é necessário implementar o método `onCreateView` aqui, o método `inflateBinding` ja faz isso.
Deve ficar da seguinte forma:
```kotlin
class ConfirmationFragment : BaseFragment<FragmentConfirmationBinding>() {

    override fun setupViews() {}

    override fun inflateBinding(
        inflater: LayoutInflater,
        container: ViewGroup?
    ): FragmentConfirmationBinding {
        return FragmentConfirmationBinding.inflate(inflater, container, false)
    }
}
```
Lembre se de remover a importações não utilizadas

2023-12-28 01:27 UTC, natanaelsc requested changes
Ótimo trabalho!!
Necessário remover somente a implementação do metodo `onCreateView`.

2024-01-04 14:08 UTC, felipemorilho commented on app/src/main/java/br/com/connectattoo/ui/confirmation/ConfirmationFragment.kt
> +    override fun onCreateView(
Importações e função removidas!

2024-01-11 10:42 UTC, natanaelsc approved these changes

2024-01-12 00:19 UTC, merged