Feature/header home
connectattoo/connectattoo.android pull request #16
Opened 2024-02-28 00:45 UTC by FlavioSabino

* create header home user

2024-02-29 00:57 UTC, natanaelsc commented on app/src/main/res/values/colors.xml
Tenta seguir um padrão para os nomes

2024-02-29 01:04 UTC, natanaelsc commented on app/src/main/java/br/com/connectattoo/ui/home/HomeUserFragment.kt
Chamar a classe BaseFragment ao invés do Fragment

2024-03-03 15:11 UTC, FlavioSabino commented
## Cabeçalho: Mensagem de Boas Vindas e Logo (Android)
* refatoração  variáveis de cores

2024-03-03 15:33 UTC, FlavioSabino commented
## Cabeçalho: Mensagem de Boas Vindas e Logo (Android)
* implementando classe Base Fragment na HomeUserFragment

2024-03-03 15:36 UTC, FlavioSabino commented on app/src/main/java/br/com/connectattoo/ui/home/HomeUserFragment.kt
concluído

2024-03-03 15:36 UTC, FlavioSabino commented on app/src/main/res/values/colors.xml
concluído

2024-03-04 22:35 UTC, natanaelsc commented on app/src/main/res/drawable/bg_butao_cancelar.xml
Olha o nome do arquivo

2024-03-04 22:35 UTC, natanaelsc commented on app/src/main/res/drawable/bg_butao_criar_conta.xml
Olha o nome do arquivo

2024-03-04 22:37 UTC, natanaelsc commented on app/src/main/java/br/com/connectattoo/ui/home/HomeUserFragment.kt
Tem algumas importações não utilizadas nesse arquivo

2024-03-04 22:39 UTC, natanaelsc requested changes
Há algumas importações não utilizadas no arquivo HomeUserFragment e também o nome dos arquivos bg_butao_cancelar e bg_butao_criar_conta precisam estar em inglês

2024-03-04 22:56 UTC, FlavioSabino commented on app/src/main/res/drawable/bg_butao_cancelar.xml
concluído

2024-03-04 23:10 UTC, natanaelsc approved these changes

2024-03-04 23:24 UTC, merged