CT-23/CT-71
connectattoo/connectattoo.android pull request #23
Opened 2024-04-09 19:31 UTC by JorgeTranin

### Localização de usuário 

- Solicita permissão de acesso a localização do usuário.
- Caso o serviço esteja desabilitado solicita ativação e faz o redirecionamento.
- Retorna localização mais próxima do usuário na tela home.
- Cria objeto para conter toda a logica de permissão e solicitação de localidade.

2024-04-10 01:13 UTC, natanaelsc commented on app/src/main/java/br/com/connectattoo/util/PermissionUtils.kt
> +    fun getPermissionAndLocationUser(
Tenta ver uma forma de quebrar esse método em pequenas funções

2024-04-10 01:22 UTC, natanaelsc commented on config/detekt/detekt.gradle
Em arquivos de configuração, sempre faça um commit especifico

2024-04-10 01:27 UTC, natanaelsc commented on app/src/main/res/values/strings.xml
> +    <string name="txt_calcel">Cancrela</string>
Sempre dá uma verifica nas linhas antes de commitar

2024-04-10 01:52 UTC, natanaelsc commented on app/src/main/java/br/com/connectattoo/util/PermissionUtils.kt
> +                            "Localização Negada!", Snackbar.LENGTH_LONG
Não é necessário retornar mensagem ao usuário

2024-04-10 01:52 UTC, natanaelsc commented on app/src/main/java/br/com/connectattoo/util/PermissionUtils.kt
> +                                    "Por favor ative a localização para uma melhor experiencia",
Não é necessário retornar mensagem ao usuário

2024-04-10 01:56 UTC, natanaelsc requested changes
* Remover mensagens de erro ou de qualquer informação ao usuário
* Corrigir erros de ortografia
* Verificar possibilidade de quebrar métodos grandes e transforma-los em reutilizáveis
* Não deve haver interações com o usuário além do pedido de permissão de localização
No geral está tudo OK. Fica atento para não fugir um pouco daquilo que foi pedido na task

2024-04-10 01:59 UTC, natanaelsc commented on app/src/main/java/br/com/connectattoo/util/PermissionUtils.kt
> +    private fun showEnableLocationDialog(
Não deve haver interações com usuário além do pedido de permissão de localização

2024-04-10 15:52 UTC, JorgeTranin commented on app/src/main/java/br/com/connectattoo/util/PermissionUtils.kt
> +    fun getPermissionAndLocationUser(
Ao remover os SnackBars a função ficou novamente pequena.

2024-04-10 15:57 UTC, JorgeTranin commented on app/src/main/java/br/com/connectattoo/util/PermissionUtils.kt
> +                            "Localização Negada!", Snackbar.LENGTH_LONG
Mensagens removidas

2024-04-11 01:38 UTC, natanaelsc approved these changes

2024-04-11 01:39 UTC, merged