CT-22/CT-111
connectattoo/connectattoo.android pull request #34
Opened 2024-04-24 21:07 UTC by JorgeTranin

### Implementar integração com API para perfil do usuário e Salvamento local

- Criado class MyAppication para conter apenas 1 instancia do Room no app.
- Criado ClientProfileDao com as funções de acesso ao Room.
- implementado o Save e Sync do perfil do usuário junto com a lista de Tags no Room DB.
- Criado classes genéricas para ser mais fácil o gerenciamento de estados dos resultados.
- Na Home Screen sempre é feito o update das informações no DB local vindos da API, se caso houver problemas os dados mandados para UI são os do DB local.
- Criado as entitys de DB e funções auxiliares de conversão e mapeamento das informações.
- Implementado o Get do perfil do cliente no DB local na tela de Perfil.
- adicionado o caractere @ ao inicio do nome de usuário (username).
- calculada a idade do usuário a partir da data de nascimento / data atual.
- verificado se o usuário possui foto no perfil. Se o usuário não possuir (“imageProfile": null) continuar sem foto no perfil.

2024-04-25 00:27 UTC, natanaelsc commented on app/src/main/java/br/com/connectattoo/api/ApiService.kt
> +import br.com.connectattoo.api.response.ClientProfileResponse
Altera para TattooClient onde tiver as ocorrências pra diferenciar tatuando de tatuador. A resposta de perfis serão diferentes.

2024-04-25 00:27 UTC, natanaelsc commented on app/src/main/java/br/com/connectattoo/api/response/ClientProfileResponse.kt
Altera para TattooClientProfile onde tiver as ocorrências de ClientProfile pra diferenciar tatuando de tatuador. A resposta de perfis serão diferentes.

2024-04-25 00:29 UTC, natanaelsc commented on app/src/main/java/br/com/connectattoo/MyApplication.kt
Será que Connectattoo não seria um nome melhor?

2024-04-25 00:30 UTC, natanaelsc commented on app/src/main/java/br/com/connectattoo/core/ResourceResult.kt
Massa!

2024-04-25 00:31 UTC, natanaelsc commented on app/src/main/java/br/com/connectattoo/data/ClientProfile.kt
Altera para TattooClientProfile onde tiver as ocorrências de ClientProfile pra diferenciar tatuando de tatuador. A resposta de perfis serão diferentes.

2024-04-25 00:32 UTC, natanaelsc commented on app/src/main/java/br/com/connectattoo/data/ClientProfileTag.kt
Altera somente para Tag. Todas as tags, independente de qualquer coisa terão as mesmas propriedades

2024-04-25 00:32 UTC, natanaelsc commented on app/src/main/java/br/com/connectattoo/local/database/AppDatabase.kt
> +    abstract fun clientProfileDao() : ClientProfileDao
Altera para TattooClientProfile onde tiver as ocorrências de ClientProfile pra diferenciar tatuando de tatuador. A resposta de perfis serão diferentes.

2024-04-25 00:33 UTC, natanaelsc commented on app/src/main/java/br/com/connectattoo/local/database/daos/ClientProfileDao.kt
> +package br.com.connectattoo.local.database.daos
Altera o nome do pacote para `dao`, sem ser no plural

2024-04-25 00:44 UTC, natanaelsc commented on app/src/main/java/br/com/connectattoo/repository/UserRepository.kt
Se o UserRepository for utilizado apenas no contexto do perfil, altera ele para ProfileRepository.

2024-04-25 00:49 UTC, natanaelsc commented on app/src/main/java/br/com/connectattoo/ui/tattooclientprofile/TattooClientProfileFragment.kt
> +            txtAgeAndDisplayName.text = viewModel.state.txtAgeAndEmail
Será que não geraria confusão com os nomes? `txtAgeAndEmail` e ` txtAgeAndDisplayName`

2024-04-25 00:52 UTC, natanaelsc commented on app/src/main/java/br/com/connectattoo/ui/tattooclientprofile/TattooClientProfileState.kt
Será que isso não poderia ficar dentro de um pacote `profile/tattooclient` ao invés de `tattooclientprofile`?

2024-04-25 00:54 UTC, natanaelsc requested changes
* Alterar ocorrências de ClientProfile para TattooClientProfile

2024-04-25 22:40 UTC, JorgeTranin commented on app/src/main/java/br/com/connectattoo/data/ClientProfileTag.kt
Somente a classe TagHomeScreen foi mantida separada, classe de modelo para o adapter. tem propriedades diferentes.

2024-04-26 00:16 UTC, natanaelsc approved these changes

2024-04-26 00:17 UTC, merged