CT-22/CT-104
connectattoo/connectattoo.android pull request #37
Opened 2024-04-28 11:22 UTC by FlavioSabino

## Adicionar navegação as de mais telas (Android)
* criar funçao de navegaçao do bottomNavigationView

2024-04-28 12:36 UTC, natanaelsc requested changes
* Resolver conflitos na branch
* Corrigir formatação das condicionais compostas

#### Observação

O commit 6167bc2fa5ab2d6c8821fdd91cbafb013f64d71d não seria um refactor já que altera o comportamento do código. Verifica [esse artigo](https://medium.com/linkapi-solutions/conventional-commits-pattern-3778d1a1e657) que fala sobre o assunto.
Na mensagem de commit, sempre dá um espaçamento entre o tipo e a descrição, por exemplo "feat: create bottomNavigationView navigation function".
No código, da um espaçamento entre os "{}" e "else if", por exemplo "} else if {".

2024-05-01 22:01 UTC, JorgeTranin commented on app/src/main/java/br/com/connectattoo/HomeUserActivity.kt
> +            binding.profileTrue.isVisible = destination.id == R.id.clientUserProfileFragment
Sugestão: Quando usar binding varias vezes um a baixo do outro é possível fazer um binding.run{ } para otimização de código.

2024-05-16 14:09 UTC, natanaelsc requested changes
* Revolver conflitos em `app/src/main/java/br/com/connectattoo/ui/home/HomeUserFragment.kt`

2024-05-17 13:26 UTC, hitoruku approved these changes

2024-05-17 13:28 UTC, natanaelsc approved these changes

2024-05-17 21:06 UTC, merged