CT-35/CT-103
connectattoo/connectattoo.android pull request #43
Opened 2024-05-04 13:37 UTC by SergioRiosRibeiro

##Cria tela "Explorar" do usuário

- ####Adiciona o layout fragment_user_search.xml
- ####Cria campo de busca com ícones de lupa e microfone
- ####Cria os arquivos/classes UserSearchFragment e UserSearchViewModel
-####Cria os arquivos/classes UserSearchAdapter e UserSearchViewHolder, setando configuração básica da RecyclerView da tela de busca

2024-05-04 22:35 UTC, JorgeTranin requested changes

2024-05-04 22:35 UTC, JorgeTranin commented on app/src/main/java/br/com/connectattoo/HomeUserActivity.kt
> +        setContentView(R.layout.fragment_home_user)
Alterar para R.layout.activity_home_user novamente.

2024-05-06 18:52 UTC, SergioRiosRibeiro commented on app/src/main/java/br/com/connectattoo/HomeUserActivity.kt
> +        setContentView(R.layout.fragment_home_user)
Feito 👍🏻

2024-05-06 18:56 UTC, SergioRiosRibeiro commented on app/src/main/java/br/com/connectattoo/HomeUserActivity.kt
> +        setContentView(R.layout.fragment_home_user)
Feito 👍🏻

2024-05-10 23:20 UTC, closed without merging